# Generated by Django 3.0.2 on 2020-01-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_people_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
        migrations.AddField(
            model_name='people',
            name='nickname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
